import './globals.css'
import { Roboto } from 'next/font/google'
import Navbar from "@/components/navbar";

import { useSelectedLayoutSegments } from 'next/navigation';
import NextAuthProvider from '@/app/context/NextAuthProvider';


 
const roboto = Roboto({
  weight: ['400', '100'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})


export const metadata = {
  title: 'Mtb forum',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
        <Navbar />
        {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}