import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/navbar";
import { Analytics } from "@vercel/analytics/react";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import NextAuthProvider from "@/app/context/NextAuthProvider";
import { SpeedInsights } from "@vercel/speed-insights/next"

const roboto = Roboto({
  weight: ["400", "100"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mtb forum",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SpeedInsights />
        <NextAuthProvider>
          <Navbar />
          {children}
          <Analytics />
        </NextAuthProvider>
      </body>
    </html>
  );
}
